create table person (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(50),
    gender VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    date_of_birth DATE NOT NULL
);

insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Danette', 'Crusham', 'dcrusham0@is.gd', 'Female', 'Afghanistan', '03/24/2017');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Kala', 'Kondratyuk', 'kkondratyuk1@wordpress.com', 'Female', 'Afghanistan', '02/14/1999');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Vivienne', 'Bultitude', 'vbultitude2@shinystat.com', 'Female', 'Afghanistan', '03/29/2012');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Meridel', 'Emanuel', 'memanuel3@chicagotribune.com', 'Female', 'Afghanistan', '04/26/1991');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Valerie', 'Foulsham', 'vfoulsham4@guardian.co.uk', 'Female', 'Afghanistan', '04/29/1992');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Madonna', 'Moen', 'mmoen5@illinois.edu', 'Female', 'Afghanistan', '12/31/1993');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Tamara', 'Sidnell', 'tsidnell6@umn.edu', 'Female', 'Afghanistan', '05/29/1998');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Haley', 'Geerits', 'hgeerits7@epa.gov', 'Female', 'Afghanistan', '11/07/1996');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Jermain', 'Ruggier', 'jruggier8@nasa.gov', 'Male', 'Afghanistan', '09/29/2010');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Judas', 'Heliot', 'jheliot9@usa.gov', 'Male', 'Afghanistan', '04/27/2012');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Sherrie', 'Jennens', 'sjennensa@webs.com', 'Female', 'Afghanistan', '01/10/2004');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Frederique', 'Hyder', null, 'Female', 'Afghanistan', '07/19/2004');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Giffard', 'Glendinning', 'gglendinningc@gov.uk', 'Genderfluid', 'Afghanistan', '09/03/1990');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Chad', 'Annies', 'canniesd@sourceforge.net', 'Male', 'Afghanistan', '01/13/1996');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Thadeus', 'Mulliner', 'tmullinere@etsy.com', 'Male', 'Afghanistan', '11/25/2005');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Roana', 'Chilcotte', 'rchilcottef@xing.com', 'Female', 'Afghanistan', '06/25/1990');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Pierre', 'Tunkin', 'ptunking@imageshack.us', 'Male', 'Afghanistan', '03/21/2001');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Milissent', 'Wardlaw', 'mwardlawh@homestead.com', 'Female', 'Afghanistan', '12/18/2010');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Trevor', 'Markey', 'tmarkeyi@nifty.com', 'Bigender', 'Afghanistan', '06/15/1999');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Ardyth', 'Bennough', 'abennoughj@yellowbook.com', 'Female', 'Afghanistan', '02/23/2023');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Thain', 'Angless', 'tanglessk@domainmarket.com', 'Male', 'Afghanistan', '02/06/2014');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Courtney', 'Vedyaev', 'cvedyaevl@zimbio.com', 'Male', 'Afghanistan', '05/08/2010');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Bobbie', 'Bainbridge', null, 'Female', 'Afghanistan', '06/01/1997');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Daria', 'Wasbrough', null, 'Genderqueer', 'Afghanistan', '11/11/2014');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Winona', 'Gilvary', 'wgilvaryo@gmpg.org', 'Agender', 'Afghanistan', '06/08/1991');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Nadine', 'Cordel', null, 'Female', 'Afghanistan', '02/01/2004');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Darryl', 'Bernaldez', 'dbernaldezq@stanford.edu', 'Female', 'Afghanistan', '09/01/2022');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Tobit', 'Charke', 'tcharker@elpais.com', 'Male', 'Afghanistan', '12/26/2021');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Siffre', 'Ebben', null, 'Male', 'Afghanistan', '02/14/2017');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Saunderson', 'Wrought', null, 'Male', 'Afghanistan', '04/04/2009');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Antone', 'Gamett', 'agamettu@census.gov', 'Male', 'Afghanistan', '01/27/1997');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Ximenes', 'Esslemont', 'xesslemontv@imdb.com', 'Male', 'Afghanistan', '02/24/1998');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Killie', 'Fahrenbacher', 'kfahrenbacherw@samsung.com', 'Male', 'Afghanistan', '10/08/2002');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Maggee', 'Radbourn', 'mradbournx@51.la', 'Female', 'Afghanistan', '03/21/2003');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Cchaddie', 'Hillatt', 'chillatty@bigcartel.com', 'Male', 'Afghanistan', '06/05/2012');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Floris', 'McCauley', 'fmccauleyz@slashdot.org', 'Female', 'Afghanistan', '10/04/1997');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Sven', 'Tritton', 'stritton10@yahoo.com', 'Male', 'Afghanistan', '02/03/2012');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Neil', 'Dyott', 'ndyott11@mlb.com', 'Male', 'Afghanistan', '02/26/2004');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Guido', 'Bodd', 'gbodd12@utexas.edu', 'Male', 'Afghanistan', '08/19/1991');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Saxe', 'Burgher', 'sburgher13@tiny.cc', 'Male', 'Afghanistan', '05/25/1992');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Carlo', 'Roskilly', 'croskilly14@goo.ne.jp', 'Male', 'Afghanistan', '03/27/1997');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Wren', 'Cobain', 'wcobain15@ihg.com', 'Female', 'Afghanistan', '07/10/2010');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Marietta', 'Bremeyer', 'mbremeyer16@globo.com', 'Male', 'Afghanistan', '11/17/2007');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Nance', 'De Beneditti', 'ndebeneditti17@admin.ch', 'Female', 'Afghanistan', '04/01/2011');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Trudey', 'Willatts', 'twillatts18@shareasale.com', 'Female', 'Afghanistan', '10/11/2006');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Lesley', 'Posselt', 'lposselt19@mozilla.org', 'Male', 'Afghanistan', '02/28/2016');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Ricardo', 'Bruhke', 'rbruhke1a@rediff.com', 'Male', 'Afghanistan', '07/16/2001');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Lauri', 'Maleham', null, 'Female', 'Afghanistan', '12/29/2005');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Krispin', 'Core', 'kcore1c@state.gov', 'Male', 'Afghanistan', '04/26/2016');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Kelley', 'Slark', 'kslark1d@arstechnica.com', 'Female', 'Afghanistan', '11/03/2002');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Benetta', 'Fradson', 'bfradson1e@hugedomains.com', 'Female', 'Afghanistan', '07/17/2009');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Drusy', 'Beddon', 'dbeddon1f@oakley.com', 'Female', 'Afghanistan', '04/25/1992');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Lila', 'Boarleyson', 'lboarleyson1g@list-manage.com', 'Female', 'Afghanistan', '01/21/2020');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Rorke', 'Cattrall', 'rcattrall1h@oaic.gov.au', 'Genderqueer', 'Afghanistan', '06/11/1991');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Flossie', 'Haversham', 'fhaversham1i@statcounter.com', 'Female', 'Afghanistan', '05/26/1998');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Shamus', 'Beechcraft', null, 'Male', 'Afghanistan', '09/24/2008');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Gian', 'Slayford', 'gslayford1k@va.gov', 'Male', 'Afghanistan', '01/18/2020');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Ulla', 'MacAfee', 'umacafee1l@loc.gov', 'Female', 'Afghanistan', '07/06/2013');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Olva', 'Devita', 'odevita1m@amazonaws.com', 'Female', 'Afghanistan', '03/01/1993');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Morse', 'Scoon', 'mscoon1n@bbb.org', 'Male', 'Afghanistan', '10/14/2012');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Brook', 'Routh', 'brouth1o@dot.gov', 'Male', 'Afghanistan', '10/01/2016');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Carroll', 'Josipovitz', 'cjosipovitz1p@bigcartel.com', 'Polygender', 'Afghanistan', '08/02/2002');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Daniel', 'Henlon', 'dhenlon1q@xing.com', 'Genderfluid', 'Afghanistan', '01/02/2013');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Licha', 'Cancellario', 'lcancellario1r@msu.edu', 'Female', 'Afghanistan', '11/26/1995');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Sanson', 'Schild', 'sschild1s@privacy.gov.au', 'Non-binary', 'Afghanistan', '08/16/2020');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Cyrus', 'Towsey', 'ctowsey1t@github.com', 'Male', 'Afghanistan', '01/17/2009');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Ema', 'Handrock', 'ehandrock1u@parallels.com', 'Female', 'Afghanistan', '04/20/2002');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Jude', 'Daymont', 'jdaymont1v@theatlantic.com', 'Male', 'Afghanistan', '08/21/1996');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Monika', 'Willmont', 'mwillmont1w@amazonaws.com', 'Female', 'Afghanistan', '10/31/2020');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Modesty', 'Leas', 'mleas1x@qq.com', 'Female', 'Afghanistan', '01/09/2015');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Grange', 'Duchesne', 'gduchesne1y@ifeng.com', 'Male', 'Afghanistan', '03/01/2010');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Shay', 'Dunlap', 'sdunlap1z@foxnews.com', 'Male', 'Afghanistan', '02/23/2010');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Bill', 'Goard', 'bgoard20@oakley.com', 'Bigender', 'Afghanistan', '01/15/1996');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Lyndell', 'Delf', 'ldelf21@patch.com', 'Female', 'Afghanistan', '04/24/2004');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Charles', 'Ferraron', 'cferraron22@lycos.com', 'Male', 'Afghanistan', '07/27/2022');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Mitzi', 'Holleran', 'mholleran23@jalbum.net', 'Female', 'Afghanistan', '11/29/2022');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Beitris', 'Warrior', null, 'Female', 'Afghanistan', '08/16/2014');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Merill', 'Cogzell', 'mcogzell25@over-blog.com', 'Male', 'Afghanistan', '07/15/2008');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Adrian', 'Webster', 'awebster26@ucoz.ru', 'Female', 'Afghanistan', '01/18/1991');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Rosabelle', 'Mineghelli', 'rmineghelli27@umn.edu', 'Female', 'Afghanistan', '08/11/2003');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Baillie', 'Chessor', 'bchessor28@wikia.com', 'Male', 'Afghanistan', '03/21/1994');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Dusty', 'Grossier', 'dgrossier29@jigsy.com', 'Female', 'Afghanistan', '02/16/2016');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Lissie', 'MacElharge', 'lmacelharge2a@naver.com', 'Female', 'Afghanistan', '01/14/2022');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Jamison', 'Melville', 'jmelville2b@tmall.com', 'Male', 'Afghanistan', '04/26/2005');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Cinda', 'Norvel', 'cnorvel2c@a8.net', 'Female', 'Afghanistan', '05/09/2000');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Garwood', 'Baiyle', 'gbaiyle2d@amazonaws.com', 'Male', 'Afghanistan', '12/23/1990');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Chilton', 'Simonson', 'csimonson2e@newsvine.com', 'Male', 'Afghanistan', '09/26/2000');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Joella', 'Denholm', 'jdenholm2f@dell.com', 'Female', 'Afghanistan', '01/11/2022');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Neils', 'Medina', null, 'Male', 'Afghanistan', '03/23/2017');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Dewitt', 'Goldes', 'dgoldes2h@time.com', 'Male', 'Afghanistan', '05/01/2021');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Belicia', 'Turbat', 'bturbat2i@plala.or.jp', 'Female', 'Afghanistan', '11/23/2003');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Bobby', 'Taggett', 'btaggett2j@sohu.com', 'Female', 'Afghanistan', '06/24/1991');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Delila', 'Heddan', 'dheddan2k@themeforest.net', 'Female', 'Afghanistan', '09/13/2011');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Olivier', 'Rash', 'orash2l@merriam-webster.com', 'Male', 'Afghanistan', '12/09/2019');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Olin', 'O''Dowd', 'oodowd2m@businessweek.com', 'Male', 'Afghanistan', '06/11/2005');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Mile', 'Kleinberer', 'mkleinberer2n@gizmodo.com', 'Male', 'Afghanistan', '03/22/2022');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Leonelle', 'Wemes', 'lwemes2o@nsw.gov.au', 'Female', 'Afghanistan', '09/10/2015');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Issie', 'Bisley', 'ibisley2p@ebay.com', 'Female', 'Afghanistan', '09/05/2018');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Wiley', 'Stit', 'wstit2q@oaic.gov.au', 'Male', 'Afghanistan', '12/20/2013');
insert into person (first_name, last_name, email, gender, country, date_of_birth) values ('Simmonds', 'Birbeck', 'sbirbeck2r@canalblog.com', 'Male', 'Afghanistan', '02/05/1994');
