create table cars (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(50) NOT NULL,
	model VARCHAR(50) NOT NULL,
	price INT NOT NULL
);
insert into cars (make, model, price) values ('Volkswagen', 'Golf', 34493);
insert into cars (make, model, price) values ('GMC', 'Yukon XL 1500', 32224);
insert into cars (make, model, price) values ('Hyundai', 'Elantra', 45986);
insert into cars (make, model, price) values ('Suzuki', 'Esteem', 39182);
insert into cars (make, model, price) values ('Chrysler', 'Crossfire', 6966);
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', 16928);
insert into cars (make, model, price) values ('Toyota', 'Avalon', 11552);
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', 9914);
insert into cars (make, model, price) values ('Mitsubishi', 'Tredia', 22652);
insert into cars (make, model, price) values ('Infiniti', 'G', 25593);
insert into cars (make, model, price) values ('Maybach', 'Landaulet', 36176);
insert into cars (make, model, price) values ('Aston Martin', 'V8 Vantage', 29196);
insert into cars (make, model, price) values ('Suzuki', 'Verona', 5594);
insert into cars (make, model, price) values ('Chevrolet', 'Avalanche 1500', 36958);
insert into cars (make, model, price) values ('Lexus', 'GS', 36780);
insert into cars (make, model, price) values ('BMW', '325', 17533);
insert into cars (make, model, price) values ('Toyota', 'Yaris', 28148);
insert into cars (make, model, price) values ('Mazda', '323', 24879);
insert into cars (make, model, price) values ('Ford', 'Mustang', 42087);
insert into cars (make, model, price) values ('Land Rover', 'Range Rover Evoque', 49524);
insert into cars (make, model, price) values ('Saturn', 'L-Series', 10378);
insert into cars (make, model, price) values ('Mercury', 'Mystique', 29133);
insert into cars (make, model, price) values ('Ford', 'F250', 21243);
insert into cars (make, model, price) values ('Porsche', 'Cayenne', 32476);
insert into cars (make, model, price) values ('Chevrolet', 'Astro', 30566);
insert into cars (make, model, price) values ('Ford', 'Thunderbird', 45672);
insert into cars (make, model, price) values ('Audi', 'S4', 34682);
insert into cars (make, model, price) values ('Nissan', 'Sentra', 22687);
insert into cars (make, model, price) values ('Toyota', 'Celica', 38507);
insert into cars (make, model, price) values ('Volvo', 'S80', 41280);
insert into cars (make, model, price) values ('Ford', 'Expedition', 6699);
insert into cars (make, model, price) values ('Nissan', 'Altima', 29075);
insert into cars (make, model, price) values ('Buick', 'Coachbuilder', 26585);
insert into cars (make, model, price) values ('Land Rover', 'Freelander', 48797);
insert into cars (make, model, price) values ('Chevrolet', 'Colorado', 9758);
insert into cars (make, model, price) values ('Dodge', 'Ram Van 1500', 18169);
insert into cars (make, model, price) values ('Lincoln', 'MKX', 43921);
insert into cars (make, model, price) values ('Lincoln', 'Continental', 34175);
insert into cars (make, model, price) values ('Ford', 'F350', 16701);
insert into cars (make, model, price) values ('GMC', 'Sonoma Club Coupe', 21979);
insert into cars (make, model, price) values ('GMC', 'Sonoma', 9791);
insert into cars (make, model, price) values ('Chevrolet', 'Tahoe', 17066);
insert into cars (make, model, price) values ('Chevrolet', 'Monte carslo', 30215);
insert into cars (make, model, price) values ('Oldsmobile', 'Silhouette', 33762);
insert into cars (make, model, price) values ('Chevrolet', 'Impala', 9811);
insert into cars (make, model, price) values ('Ford', 'F-Series Super Duty', 16027);
insert into cars (make, model, price) values ('Mitsubishi', 'Lancer', 18740);
insert into cars (make, model, price) values ('Ford', 'Mustang', 5334);
insert into cars (make, model, price) values ('Mercedes-Benz', 'S-Class', 41516);
insert into cars (make, model, price) values ('Mitsubishi', 'Cordia', 40170);
insert into cars (make, model, price) values ('Saturn', 'L-Series', 30678);
insert into cars (make, model, price) values ('Mitsubishi', 'Tredia', 7263);
insert into cars (make, model, price) values ('Ford', 'EXP', 32404);
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 2500', 21866);
insert into cars (make, model, price) values ('Volvo', 'XC70', 25730);
insert into cars (make, model, price) values ('Kia', 'Mohave/Borrego', 28124);
insert into cars (make, model, price) values ('Mazda', '626', 25374);
insert into cars (make, model, price) values ('Ford', 'F350', 25228);
insert into cars (make, model, price) values ('Volkswagen', 'Golf', 39464);
insert into cars (make, model, price) values ('Mitsubishi', 'Chariot', 20819);
insert into cars (make, model, price) values ('GMC', 'Sonoma Club Coupe', 48247);
insert into cars (make, model, price) values ('Audi', 'A6', 39303);
insert into cars (make, model, price) values ('Audi', '200', 9916);
insert into cars (make, model, price) values ('GMC', 'Yukon XL 1500', 49881);
insert into cars (make, model, price) values ('Mercedes-Benz', 'CL-Class', 40271);
insert into cars (make, model, price) values ('Infiniti', 'FX', 29278);
insert into cars (make, model, price) values ('Saab', '9-7X', 48164);
insert into cars (make, model, price) values ('Infiniti', 'Q', 12805);
insert into cars (make, model, price) values ('Nissan', 'Armada', 43346);
insert into cars (make, model, price) values ('Maserati', '430', 8556);
insert into cars (make, model, price) values ('Mitsubishi', 'Montero', 28375);
insert into cars (make, model, price) values ('Isuzu', 'Rodeo', 45216);
insert into cars (make, model, price) values ('Suzuki', 'Grand Vitara', 44768);
insert into cars (make, model, price) values ('Buick', 'Skylark', 30003);
insert into cars (make, model, price) values ('Saab', '900', 13657);
insert into cars (make, model, price) values ('Porsche', 'Cayman', 21603);
insert into cars (make, model, price) values ('Hyundai', 'Santa Fe', 6256);
insert into cars (make, model, price) values ('Mercedes-Benz', 'CLK-Class', 32619);
insert into cars (make, model, price) values ('Kia', 'Mentor', 47360);
insert into cars (make, model, price) values ('Cadillac', 'XLR-V', 25282);
insert into cars (make, model, price) values ('BMW', '600', 42648);
insert into cars (make, model, price) values ('Dodge', 'Dakota', 33164);
insert into cars (make, model, price) values ('Mazda', 'B-Series', 33622);
insert into cars (make, model, price) values ('Suzuki', 'XL-7', 38862);
insert into cars (make, model, price) values ('Mazda', 'MPV', 35763);
insert into cars (make, model, price) values ('Lexus', 'IS', 6580);
insert into cars (make, model, price) values ('Rolls-Royce', 'Phantom', 14603);
insert into cars (make, model, price) values ('Cadillac', 'XLR', 8439);
insert into cars (make, model, price) values ('Maybach', '57', 10337);
insert into cars (make, model, price) values ('Dodge', 'Neon', 28753);
insert into cars (make, model, price) values ('Plymouth', 'Voyager', 49822);
insert into cars (make, model, price) values ('Mazda', 'Protege', 40099);
insert into cars (make, model, price) values ('Ram', '2500', 13014);
insert into cars (make, model, price) values ('BMW', '7 Series', 20051);
insert into cars (make, model, price) values ('Chrysler', 'Aspen', 37144);
insert into cars (make, model, price) values ('Lincoln', 'Navigator L', 7509);
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 2500', 36760);
insert into cars (make, model, price) values ('BMW', 'X5 M', 28457);
insert into cars (make, model, price) values ('Audi', 'Q7', 12258);
insert into cars (make, model, price) values ('Chevrolet', 'TrailBlazer', 15228);
insert into cars (make, model, price) values ('Ford', 'Explorer Sport Trac', 7141);
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', 41205);
insert into cars (make, model, price) values ('Kia', 'Mentor', 35591);
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 1500', 30235);
insert into cars (make, model, price) values ('Subaru', 'Forester', 6821);
insert into cars (make, model, price) values ('Mazda', 'B-Series', 32917);
insert into cars (make, model, price) values ('Land Rover', 'Freelander', 25279);
insert into cars (make, model, price) values ('Spyker', 'C8 Spyder Wide Body', 30263);
insert into cars (make, model, price) values ('Eagle', 'Summit', 29645);
insert into cars (make, model, price) values ('GMC', 'Yukon', 49604);
insert into cars (make, model, price) values ('Ford', 'F250', 28220);
insert into cars (make, model, price) values ('Honda', 'Accord Crosstour', 49467);
insert into cars (make, model, price) values ('Mercedes-Benz', 'C-Class', 10371);
insert into cars (make, model, price) values ('Ford', 'Taurus', 8838);
insert into cars (make, model, price) values ('Ford', 'Excursion', 34467);
insert into cars (make, model, price) values ('Volvo', '850', 45743);
insert into cars (make, model, price) values ('Saab', '900', 42647);
insert into cars (make, model, price) values ('Lexus', 'RX', 26512);
insert into cars (make, model, price) values ('Pontiac', 'Trans Sport', 13732);
insert into cars (make, model, price) values ('Pontiac', 'LeMans', 44204);
insert into cars (make, model, price) values ('Ford', 'Windstar', 26058);
insert into cars (make, model, price) values ('Kia', 'Sephia', 45591);
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', 46569);
insert into cars (make, model, price) values ('Audi', 'A7', 36623);
insert into cars (make, model, price) values ('Audi', 'A4', 35312);
insert into cars (make, model, price) values ('Subaru', 'Justy', 10771);
insert into cars (make, model, price) values ('Maserati', 'Quattroporte', 21259);
insert into cars (make, model, price) values ('Mercedes-Benz', 'Sprinter', 6619);
insert into cars (make, model, price) values ('Acura', 'RL', 23611);
insert into cars (make, model, price) values ('Cadillac', 'Escalade', 30063);
insert into cars (make, model, price) values ('Chevrolet', 'Bel Air', 30900);
insert into cars (make, model, price) values ('Chevrolet', 'Tahoe', 12567);
insert into cars (make, model, price) values ('Porsche', 'Boxster', 40162);
insert into cars (make, model, price) values ('GMC', 'Savana 3500', 43841);
insert into cars (make, model, price) values ('Jeep', 'Grand Cherokee', 13240);
insert into cars (make, model, price) values ('Ford', 'Explorer Sport Trac', 28236);
insert into cars (make, model, price) values ('GMC', 'Sierra 2500', 40013);
insert into cars (make, model, price) values ('Volvo', 'S60', 34599);
insert into cars (make, model, price) values ('Buick', 'Regal', 37425);
insert into cars (make, model, price) values ('Isuzu', 'Amigo', 5584);
insert into cars (make, model, price) values ('Saab', '900', 12781);
insert into cars (make, model, price) values ('Toyota', 'Previa', 28868);
insert into cars (make, model, price) values ('Dodge', 'Dakota Club', 39278);
insert into cars (make, model, price) values ('Nissan', 'Altima', 6145);
insert into cars (make, model, price) values ('Oldsmobile', 'Ciera', 37921);
insert into cars (make, model, price) values ('Oldsmobile', '88', 21927);
insert into cars (make, model, price) values ('Ferrari', '458 Italia', 45319);
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 46997);
insert into cars (make, model, price) values ('Kia', 'Sportage', 35567);
insert into cars (make, model, price) values ('Kia', 'Sedona', 49954);
insert into cars (make, model, price) values ('Buick', 'Riviera', 44362);
insert into cars (make, model, price) values ('Dodge', 'Ram 1500 Club', 5516);
insert into cars (make, model, price) values ('Audi', '5000S', 32772);
insert into cars (make, model, price) values ('Scion', 'tC', 6756);
insert into cars (make, model, price) values ('Lincoln', 'Continental', 38018);
insert into cars (make, model, price) values ('Mitsubishi', 'Mirage', 43479);
insert into cars (make, model, price) values ('Mazda', 'Miata MX-5', 28267);
insert into cars (make, model, price) values ('Acura', 'TL', 27773);
insert into cars (make, model, price) values ('Infiniti', 'M', 49113);
insert into cars (make, model, price) values ('Mazda', 'Mazdaspeed 3', 22696);
insert into cars (make, model, price) values ('Honda', 'CR-V', 30999);
insert into cars (make, model, price) values ('Toyota', 'Prius', 46733);
insert into cars (make, model, price) values ('BMW', '645', 18168);
insert into cars (make, model, price) values ('Lexus', 'LX', 35213);
insert into cars (make, model, price) values ('Audi', 'A8', 19531);
insert into cars (make, model, price) values ('Toyota', 'Paseo', 42950);
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', 7978);
insert into cars (make, model, price) values ('Nissan', 'Altima', 19993);
insert into cars (make, model, price) values ('Honda', 'Pilot', 45987);
insert into cars (make, model, price) values ('GMC', '1500', 35993);
insert into cars (make, model, price) values ('Mazda', 'Mazdaspeed 3', 32324);
insert into cars (make, model, price) values ('Acura', 'SLX', 9263);
insert into cars (make, model, price) values ('Mercedes-Benz', 'CL-Class', 46468);
insert into cars (make, model, price) values ('Mitsubishi', 'Mirage', 29911);
insert into cars (make, model, price) values ('Cadillac', 'CTS', 42169);
insert into cars (make, model, price) values ('GMC', 'Yukon XL', 35984);
insert into cars (make, model, price) values ('Pontiac', 'Fiero', 37707);
insert into cars (make, model, price) values ('Jaguar', 'S-Type', 11299);
insert into cars (make, model, price) values ('Pontiac', 'G6', 30608);
insert into cars (make, model, price) values ('Ford', 'EXP', 40601);
insert into cars (make, model, price) values ('Ford', 'Taurus', 26054);
insert into cars (make, model, price) values ('Ford', 'Bronco II', 44785);
insert into cars (make, model, price) values ('Ford', 'Probe', 48481);
insert into cars (make, model, price) values ('Cadillac', 'Eldorado', 37619);
insert into cars (make, model, price) values ('Hyundai', 'XG350', 29415);
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 2500', 8175);
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 3500', 29226);
insert into cars (make, model, price) values ('Chevrolet', 'Impala', 13492);
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', 14413);
insert into cars (make, model, price) values ('Mercury', 'Lynx', 42716);
insert into cars (make, model, price) values ('Chevrolet', 'Express', 26831);
insert into cars (make, model, price) values ('Lotus', 'Esprit', 40508);
insert into cars (make, model, price) values ('Infiniti', 'QX', 25139);
insert into cars (make, model, price) values ('Audi', 'S4', 40206);
insert into cars (make, model, price) values ('BMW', '525', 48960);
insert into cars (make, model, price) values ('Audi', 'TT', 34065);
insert into cars (make, model, price) values ('Subaru', 'Forester', 7223);
insert into cars (make, model, price) values ('GMC', 'Savana 1500', 25578);
insert into cars (make, model, price) values ('Chevrolet', 'Express 2500', 9917);
insert into cars (make, model, price) values ('Cadillac', 'CTS', 16633);
insert into cars (make, model, price) values ('Lexus', 'LS', 38741);
insert into cars (make, model, price) values ('Ford', 'Bronco II', 20912);
insert into cars (make, model, price) values ('Lincoln', 'Mark VIII', 25593);
insert into cars (make, model, price) values ('Jeep', 'Commander', 29783);
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', 49272);
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', 23273);
insert into cars (make, model, price) values ('GMC', 'Savana 1500', 12064);
insert into cars (make, model, price) values ('Porsche', '928', 45471);
insert into cars (make, model, price) values ('Acura', 'MDX', 45327);
insert into cars (make, model, price) values ('Mazda', 'MX-5', 8097);
insert into cars (make, model, price) values ('GMC', 'Sierra 3500', 12681);
insert into cars (make, model, price) values ('Maybach', '57', 34242);
insert into cars (make, model, price) values ('Chevrolet', 'Express', 21939);
insert into cars (make, model, price) values ('Suzuki', 'Forenza', 24286);
insert into cars (make, model, price) values ('Lotus', 'Elise', 17278);
insert into cars (make, model, price) values ('Infiniti', 'G25', 23757);
insert into cars (make, model, price) values ('Ford', 'Bronco', 10924);
insert into cars (make, model, price) values ('Audi', '5000S', 38969);
insert into cars (make, model, price) values ('Chevrolet', 'Tahoe', 47911);
insert into cars (make, model, price) values ('Dodge', 'Ram 50', 11803);
insert into cars (make, model, price) values ('Volkswagen', 'rio', 32625);
insert into cars (make, model, price) values ('Cadillac', 'DeVille', 8439);
insert into cars (make, model, price) values ('Ford', 'E-Series', 37111);
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', 24539);
insert into cars (make, model, price) values ('Hyundai', 'Sonata', 29306);
insert into cars (make, model, price) values ('Infiniti', 'FX', 14713);
insert into cars (make, model, price) values ('Land Rover', 'Range Rover', 47130);
insert into cars (make, model, price) values ('GMC', '3500', 19927);
insert into cars (make, model, price) values ('Dodge', 'Ram 1500 Club', 33592);
insert into cars (make, model, price) values ('Mercury', 'Mountaineer', 41922);
insert into cars (make, model, price) values ('Mazda', '626', 6349);
insert into cars (make, model, price) values ('Toyota', 'TundraMax', 5698);
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', 11756);
insert into cars (make, model, price) values ('Toyota', 'Matrix', 27955);
insert into cars (make, model, price) values ('Mitsubishi', 'Montero Sport', 21639);
insert into cars (make, model, price) values ('Lexus', 'GS', 9573);
insert into cars (make, model, price) values ('Ford', 'Fusion', 22908);
insert into cars (make, model, price) values ('Infiniti', 'G35', 47575);
insert into cars (make, model, price) values ('Dodge', 'Dakota', 27987);
insert into cars (make, model, price) values ('Ford', 'Ranger', 48355);
insert into cars (make, model, price) values ('Ford', 'Econoline E350', 5209);
insert into cars (make, model, price) values ('Mercedes-Benz', 'CLK-Class', 48166);
insert into cars (make, model, price) values ('Jeep', 'Wrangler', 30723);
insert into cars (make, model, price) values ('GMC', 'Sierra 3500', 39029);
insert into cars (make, model, price) values ('Buick', 'Riviera', 15659);
insert into cars (make, model, price) values ('Mazda', 'RX-7', 9624);
insert into cars (make, model, price) values ('Oldsmobile', 'Alero', 23045);
insert into cars (make, model, price) values ('Volkswagen', 'GTI', 19035);
insert into cars (make, model, price) values ('Mercury', 'Cougar', 13229);
insert into cars (make, model, price) values ('Chevrolet', 'TrailBlazer', 47662);
insert into cars (make, model, price) values ('Dodge', 'Grand carsavan', 16454);
insert into cars (make, model, price) values ('Land Rover', 'Range Rover', 35518);
insert into cars (make, model, price) values ('BMW', '5 Series', 36739);
insert into cars (make, model, price) values ('Infiniti', 'G', 31378);
insert into cars (make, model, price) values ('Lexus', 'SC', 36699);
insert into cars (make, model, price) values ('Chrysler', 'Concorde', 10426);
insert into cars (make, model, price) values ('Buick', 'Skylark', 17789);
insert into cars (make, model, price) values ('Jaguar', 'XJ Series', 45419);
insert into cars (make, model, price) values ('Mercury', 'Marquis', 47616);
insert into cars (make, model, price) values ('BMW', 'Z3', 7169);
insert into cars (make, model, price) values ('Lincoln', 'Continental Mark VII', 29237);
insert into cars (make, model, price) values ('Chevrolet', 'Astro', 12621);
insert into cars (make, model, price) values ('Volvo', 'V50', 33836);
insert into cars (make, model, price) values ('Dodge', 'Charger', 17006);
insert into cars (make, model, price) values ('Mazda', 'MX-5', 47974);
insert into cars (make, model, price) values ('Mitsubishi', 'Diamante', 29363);
insert into cars (make, model, price) values ('Lotus', 'Esprit', 38181);
insert into cars (make, model, price) values ('Volkswagen', 'Golf', 30275);
insert into cars (make, model, price) values ('Dodge', 'Ram 50', 46479);
insert into cars (make, model, price) values ('BMW', '7 Series', 9973);
insert into cars (make, model, price) values ('Ford', 'E-Series', 28635);
insert into cars (make, model, price) values ('Ford', 'Expedition', 17864);
insert into cars (make, model, price) values ('Nissan', 'Sentra', 9549);
insert into cars (make, model, price) values ('Mazda', 'Protege5', 47441);
insert into cars (make, model, price) values ('Kia', 'Sportage', 6603);
insert into cars (make, model, price) values ('Nissan', 'Xterra', 46437);
insert into cars (make, model, price) values ('Mercury', 'Grand Marquis', 49308);
insert into cars (make, model, price) values ('Maserati', '430', 44021);
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', 7227);
insert into cars (make, model, price) values ('Saab', '900', 18869);
insert into cars (make, model, price) values ('Volkswagen', 'New Beetle', 32219);
insert into cars (make, model, price) values ('Volvo', '960', 40448);
insert into cars (make, model, price) values ('Chrysler', 'PT Cruiser', 19223);
insert into cars (make, model, price) values ('Mercedes-Benz', 'C-Class', 32578);
insert into cars (make, model, price) values ('Suzuki', 'Reno', 25197);
insert into cars (make, model, price) values ('Chevrolet', 'Equinox', 7135);
insert into cars (make, model, price) values ('Mercury', 'Cougar', 42165);
insert into cars (make, model, price) values ('Dodge', 'Ram 1500', 39311);
insert into cars (make, model, price) values ('Dodge', 'Caliber', 9796);
insert into cars (make, model, price) values ('Volkswagen', 'Eurovan', 33493);
insert into cars (make, model, price) values ('Mercury', 'Mountaineer', 20712);
insert into cars (make, model, price) values ('Toyota', 'Tacoma', 38101);
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', 37105);
insert into cars (make, model, price) values ('Mercury', 'Grand Marquis', 5709);
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', 9927);
insert into cars (make, model, price) values ('Dodge', 'Neon', 8403);
insert into cars (make, model, price) values ('Infiniti', 'G', 41204);
insert into cars (make, model, price) values ('Dodge', 'Daytona', 48904);
insert into cars (make, model, price) values ('Mazda', 'RX-7', 35988);
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', 32470);
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', 48694);
insert into cars (make, model, price) values ('Mercedes-Benz', 'W201', 26475);
insert into cars (make, model, price) values ('Chevrolet', 'Express 2500', 5527);
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', 29020);
insert into cars (make, model, price) values ('Chevrolet', 'Equinox', 40529);
insert into cars (make, model, price) values ('Scion', 'tC', 32329);
insert into cars (make, model, price) values ('Mercury', 'Sable', 5552);
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', 21876);
insert into cars (make, model, price) values ('Chrysler', 'LHS', 9605);
insert into cars (make, model, price) values ('Toyota', 'Tacoma Xtra', 19048);
insert into cars (make, model, price) values ('Lexus', 'ES', 43274);
insert into cars (make, model, price) values ('Audi', 'S4', 16844);
insert into cars (make, model, price) values ('Chevrolet', 'Colorado', 49110);
insert into cars (make, model, price) values ('Isuzu', 'Ascender', 35602);
insert into cars (make, model, price) values ('Mazda', 'MPV', 43014);
insert into cars (make, model, price) values ('Audi', 'S4', 34743);
insert into cars (make, model, price) values ('Mitsubishi', 'Lancer', 47404);
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', 42929);
insert into cars (make, model, price) values ('Dodge', 'Stratus', 27357);
insert into cars (make, model, price) values ('GMC', 'Savana 3500', 47530);
insert into cars (make, model, price) values ('Audi', 'A8', 36274);
insert into cars (make, model, price) values ('Dodge', 'Sprinter', 36089);
insert into cars (make, model, price) values ('Subaru', 'Outback', 42241);
insert into cars (make, model, price) values ('Mitsubishi', '3000GT', 36411);
insert into cars (make, model, price) values ('Chevrolet', 'Express 2500', 31818);
insert into cars (make, model, price) values ('Suzuki', 'Swift', 32191);
insert into cars (make, model, price) values ('Kia', 'Sportage', 36948);
insert into cars (make, model, price) values ('Pontiac', 'Sunfire', 45655);
insert into cars (make, model, price) values ('Aston Martin', 'DB9', 22384);
insert into cars (make, model, price) values ('Mazda', 'CX-9', 8482);
insert into cars (make, model, price) values ('Hyundai', 'Elantra', 16229);
insert into cars (make, model, price) values ('Saturn', 'Aura', 19837);
insert into cars (make, model, price) values ('Toyota', 'Matrix', 24032);
insert into cars (make, model, price) values ('BMW', 'X5', 49480);
insert into cars (make, model, price) values ('Toyota', '4Runner', 18297);
insert into cars (make, model, price) values ('BMW', 'M3', 33332);
insert into cars (make, model, price) values ('Chevrolet', 'Cobalt SS', 17756);
insert into cars (make, model, price) values ('Lincoln', 'Navigator L', 9505);
insert into cars (make, model, price) values ('Pontiac', 'LeMans', 10779);
insert into cars (make, model, price) values ('Ford', 'Mustang', 13637);
insert into cars (make, model, price) values ('GMC', 'Envoy XL', 46187);
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', 48623);
insert into cars (make, model, price) values ('Mercedes-Benz', 'S-Class', 23408);
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', 36107);
insert into cars (make, model, price) values ('Lexus', 'IS', 38987);
insert into cars (make, model, price) values ('Lexus', 'SC', 31088);
insert into cars (make, model, price) values ('GMC', '2500 Club Coupe', 27651);
insert into cars (make, model, price) values ('Suzuki', 'Forenza', 16667);
insert into cars (make, model, price) values ('Pontiac', 'Firebird', 11415);
insert into cars (make, model, price) values ('Lincoln', 'LS', 45330);
insert into cars (make, model, price) values ('Audi', 'S4', 34085);
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', 40342);
insert into cars (make, model, price) values ('Nissan', 'Sentra', 19367);
insert into cars (make, model, price) values ('Pontiac', 'Firebird', 21989);
insert into cars (make, model, price) values ('Chevrolet', 'Tracker', 41541);
insert into cars (make, model, price) values ('Volkswagen', 'Fox', 22670);
insert into cars (make, model, price) values ('Jeep', 'Patriot', 43986);
insert into cars (make, model, price) values ('Buick', 'Electra', 5211);
insert into cars (make, model, price) values ('Mercury', 'Tracer', 15361);
insert into cars (make, model, price) values ('Chevrolet', 'Express 3500', 15031);
insert into cars (make, model, price) values ('Ford', 'Escape', 18362);
insert into cars (make, model, price) values ('Mazda', '626', 25440);
insert into cars (make, model, price) values ('Ford', 'Taurus', 16906);
insert into cars (make, model, price) values ('Lexus', 'LX', 13293);
insert into cars (make, model, price) values ('Lexus', 'LS', 32603);
insert into cars (make, model, price) values ('Ford', 'Ranger', 23998);
insert into cars (make, model, price) values ('Lexus', 'ES', 11748);
insert into cars (make, model, price) values ('Honda', 'Pilot', 25598);
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', 42127);
insert into cars (make, model, price) values ('Volvo', 'C30', 14191);
insert into cars (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', 35885);
insert into cars (make, model, price) values ('Mazda', 'CX-9', 14438);
insert into cars (make, model, price) values ('Chrysler', 'LHS', 34504);
insert into cars (make, model, price) values ('Volvo', 'V70', 9459);
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', 9172);
insert into cars (make, model, price) values ('Ford', 'E350', 38406);
insert into cars (make, model, price) values ('Saab', '9-5', 15326);
insert into cars (make, model, price) values ('Kia', 'Sportage', 14119);
insert into cars (make, model, price) values ('Mercury', 'Grand Marquis', 7936);
insert into cars (make, model, price) values ('Chevrolet', 'Express 3500', 34330);
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', 33807);
insert into cars (make, model, price) values ('GMC', 'Savana 3500', 21587);
insert into cars (make, model, price) values ('Suzuki', 'Forenza', 16484);
insert into cars (make, model, price) values ('Chrysler', 'Crossfire', 22945);
insert into cars (make, model, price) values ('Saab', '9-5', 22854);
insert into cars (make, model, price) values ('Kia', 'Forte', 23681);
insert into cars (make, model, price) values ('Dodge', 'Dakota', 30083);
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', 25744);
insert into cars (make, model, price) values ('Mazda', '323', 6245);
insert into cars (make, model, price) values ('Volkswagen', 'Passat', 26008);
insert into cars (make, model, price) values ('Volkswagen', 'Golf', 7626);
insert into cars (make, model, price) values ('Lexus', 'GS', 28479);
insert into cars (make, model, price) values ('Cadillac', 'Escalade ESV', 42993);
insert into cars (make, model, price) values ('Ford', 'Thunderbird', 40071);
insert into cars (make, model, price) values ('Ford', 'Mustang', 16991);
insert into cars (make, model, price) values ('BMW', 'M', 15302);
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', 49758);
insert into cars (make, model, price) values ('Lamborghini', 'Countach', 13141);
insert into cars (make, model, price) values ('Mercedes-Benz', 'E-Class', 11377);
insert into cars (make, model, price) values ('Ford', 'LTD Crown Victoria', 19647);
insert into cars (make, model, price) values ('Mazda', '626', 25708);
insert into cars (make, model, price) values ('Volkswagen', 'GTI', 49493);
insert into cars (make, model, price) values ('Mitsubishi', '3000GT', 46696);
insert into cars (make, model, price) values ('Lincoln', 'Aviator', 5414);
insert into cars (make, model, price) values ('GMC', 'Sonoma', 28398);
insert into cars (make, model, price) values ('Dodge', 'Durango', 49500);
insert into cars (make, model, price) values ('Holden', 'Monaro', 15503);
insert into cars (make, model, price) values ('Chrysler', 'Concorde', 19602);
insert into cars (make, model, price) values ('Saturn', 'Astra', 41893);
insert into cars (make, model, price) values ('Volvo', 'C30', 18709);
insert into cars (make, model, price) values ('Dodge', 'Viper RT/10', 40181);
insert into cars (make, model, price) values ('Ford', 'Taurus', 14317);
insert into cars (make, model, price) values ('MINI', 'Cooper Clubman', 37323);
insert into cars (make, model, price) values ('Hyundai', 'Elantra', 21566);
insert into cars (make, model, price) values ('Jeep', 'Liberty', 29967);
insert into cars (make, model, price) values ('Mercury', 'Lynx', 32160);
insert into cars (make, model, price) values ('Lexus', 'LX', 40078);
insert into cars (make, model, price) values ('Suzuki', 'Esteem', 35680);
insert into cars (make, model, price) values ('Ford', 'Thunderbird', 38967);
insert into cars (make, model, price) values ('Mitsubishi', 'Montero Sport', 29700);
insert into cars (make, model, price) values ('Dodge', 'Grand carsavan', 8423);
insert into cars (make, model, price) values ('Nissan', '350Z', 45454);
insert into cars (make, model, price) values ('Chevrolet', 'Express 1500', 30881);
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 19493);
insert into cars (make, model, price) values ('BMW', '6 Series', 6808);
insert into cars (make, model, price) values ('Toyota', 'RAV4', 10346);
insert into cars (make, model, price) values ('Toyota', 'Tundra', 42324);
insert into cars (make, model, price) values ('Chrysler', '300', 26078);
insert into cars (make, model, price) values ('Mitsubishi', 'Endeavor', 14198);
insert into cars (make, model, price) values ('GMC', '2500 Club Coupe', 27957);
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', 26028);
insert into cars (make, model, price) values ('Porsche', 'Boxster', 19771);
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', 12907);
insert into cars (make, model, price) values ('Dodge', 'Spirit', 18945);
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', 31705);
insert into cars (make, model, price) values ('Dodge', 'Ram 1500', 24040);
insert into cars (make, model, price) values ('Mercury', 'Marquis', 26256);
insert into cars (make, model, price) values ('Mercedes-Benz', 'E-Class', 16172);
insert into cars (make, model, price) values ('Ford', 'Mustang', 38019);
insert into cars (make, model, price) values ('GMC', 'Yukon XL 2500', 17266);
insert into cars (make, model, price) values ('Jeep', 'Grand Cherokee', 12548);
insert into cars (make, model, price) values ('Chevrolet', 'Traverse', 39038);
insert into cars (make, model, price) values ('BMW', '7 Series', 22610);
insert into cars (make, model, price) values ('Isuzu', 'Amigo', 5167);
insert into cars (make, model, price) values ('Lincoln', 'MKT', 49930);
insert into cars (make, model, price) values ('Dodge', 'Intrepid', 27767);
insert into cars (make, model, price) values ('Mercedes-Benz', 'CL-Class', 12086);
insert into cars (make, model, price) values ('Honda', 'Passport', 47337);
insert into cars (make, model, price) values ('Dodge', 'Ram 3500', 41091);
insert into cars (make, model, price) values ('Land Rover', 'Freelander', 20572);
insert into cars (make, model, price) values ('Toyota', 'Highlander', 46122);
insert into cars (make, model, price) values ('Honda', 'Prelude', 10556);
insert into cars (make, model, price) values ('Kia', 'Sorento', 22338);
insert into cars (make, model, price) values ('Honda', 'Accord', 24773);
insert into cars (make, model, price) values ('Saab', '9-3', 47517);
insert into cars (make, model, price) values ('Mazda', 'Tribute', 27068);
insert into cars (make, model, price) values ('Porsche', '911', 45203);
insert into cars (make, model, price) values ('Volkswagen', 'Type 2', 12434);
insert into cars (make, model, price) values ('Cadillac', 'Catera', 29385);
insert into cars (make, model, price) values ('Dodge', 'Ram 1500', 40892);
insert into cars (make, model, price) values ('Ford', 'Windstar', 49033);
insert into cars (make, model, price) values ('Ford', 'F150', 5195);
insert into cars (make, model, price) values ('Lexus', 'ES', 15330);
insert into cars (make, model, price) values ('Ram', '2500', 30423);
insert into cars (make, model, price) values ('Chevrolet', 'S10 Blazer', 19808);
insert into cars (make, model, price) values ('Chevrolet', 'Malibu', 12146);
insert into cars (make, model, price) values ('Nissan', 'Versa', 9938);
insert into cars (make, model, price) values ('MINI', 'Cooper Clubman', 43442);
insert into cars (make, model, price) values ('Dodge', 'Dakota', 19176);
insert into cars (make, model, price) values ('GMC', 'Sonoma', 32095);
insert into cars (make, model, price) values ('Honda', 'Accord', 41272);
insert into cars (make, model, price) values ('Ford', 'Aspire', 16223);
insert into cars (make, model, price) values ('Kia', 'Optima', 23189);
insert into cars (make, model, price) values ('Lincoln', 'Navigator', 36284);
insert into cars (make, model, price) values ('Jeep', 'Liberty', 34321);
insert into cars (make, model, price) values ('Buick', 'Century', 27832);
insert into cars (make, model, price) values ('Ford', 'E-Series', 30992);
insert into cars (make, model, price) values ('Suzuki', 'Swift', 6970);
insert into cars (make, model, price) values ('Saab', '9-5', 47112);
insert into cars (make, model, price) values ('Lexus', 'LX', 13308);
insert into cars (make, model, price) values ('Ford', 'Ranger', 39639);
insert into cars (make, model, price) values ('Lincoln', 'Town cars', 43572);
insert into cars (make, model, price) values ('Toyota', 'FJ Cruiser', 26587);
insert into cars (make, model, price) values ('Audi', 'A6', 11860);
insert into cars (make, model, price) values ('Mercury', 'Grand Marquis', 35805);
insert into cars (make, model, price) values ('Pontiac', 'Tempest', 18776);
insert into cars (make, model, price) values ('Suzuki', 'SJ', 26669);
insert into cars (make, model, price) values ('Pontiac', 'Vibe', 16512);
insert into cars (make, model, price) values ('Jeep', 'Compass', 8498);
insert into cars (make, model, price) values ('Chevrolet', 'Express 3500', 25734);
insert into cars (make, model, price) values ('Audi', 'A8', 26931);
insert into cars (make, model, price) values ('Kia', 'Spectra', 45705);
insert into cars (make, model, price) values ('Ford', 'GT', 41175);
insert into cars (make, model, price) values ('Mercedes-Benz', 'E-Class', 16977);
insert into cars (make, model, price) values ('Ford', 'Expedition', 33747);
insert into cars (make, model, price) values ('Isuzu', 'i-290', 27580);
insert into cars (make, model, price) values ('Isuzu', 'i-Series', 10541);
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 35287);
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', 35443);
insert into cars (make, model, price) values ('Hyundai', 'Tiburon', 47308);
